arch:
    - amd64
    - ppc64le
language: node_js
node_js:
    - "node"

# Only install test-related modules on older Node versions
install: npm run-script test-install

jobs:
    include:
        - name: webpack
          node_js: "node"
          install: cd test/webpack; npm install
          script: npm test
          arch: amd64

        - name: node-web-backend
          node_js: "node"
          script: npm run-script test-node-web
          arch: amd64

        - name: linters
          node_js: "node"
          install: npm install
          script:
              - eslint --max-warnings 0 .
              - prettier --check .
          arch: amd64
        
        - name: webpack
          node_js: "node"
          install: cd test/webpack; npm install
          script: npm test
          arch: ppc64le

        - name: node-web-backend
          node_js: "node"
          script: npm run-script test-node-web
          arch: ppc64le

        - name: linters
          node_js: "node"
          install: npm install
          script:
              - eslint --max-warnings 0 .
              - prettier --check .
          arch: ppc64le
        
          
